import {
  UserProfile,
  Project,
  ProjectDocument,
  Requirement,
  Conflict,
  Task,
  GitHubRepoInfo,
  KnowledgeEntity,
  KnowledgeRelation,
  MemoryItem,
  Conversation,
  NotificationItem,
  WorkflowJob,
  AISuggestion,
} from '@/types';

export const initialUserProfile: UserProfile = {
  id: 'usr-default-01',
  name: 'Alex Rivera',
  email: 'alex.rivera@dev.hayyuu.ai',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  githubConnected: true,
  githubUsername: 'arivera-dev',
  joinedAt: '2026-01-15T08:30:00Z',
};

export const initialProjects: Project[] = [
  {
    id: 'proj-novapay',
    name: 'NovaPay Core Engine',
    key: 'NOVA',
    description: 'High-throughput microservices backend for cross-border transaction settlement with real-time fraud scoring.',
    repositoryUrl: 'https://github.com/hayyuu-ai/novapay-core',
    branch: 'main',
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-08-09T14:22:00Z',
    status: 'Active',
    documentsCount: 5,
    requirementsCount: 8,
    tasksCount: 7,
    conflictsCount: 2,
    memoriesCount: 9,
    knowledgeEntitiesCount: 12,
  },
  {
    id: 'proj-authservice',
    name: 'AuthService Go',
    key: 'AUTH',
    description: 'Zero-trust OAuth2 / OIDC identity provider with WebAuthn support and fine-grained ABAC token enforcement.',
    repositoryUrl: 'https://github.com/hayyuu-ai/auth-service',
    branch: 'main',
    createdAt: '2026-03-12T09:15:00Z',
    updatedAt: '2026-08-08T11:05:00Z',
    status: 'Active',
    documentsCount: 3,
    requirementsCount: 5,
    tasksCount: 4,
    conflictsCount: 1,
    memoriesCount: 5,
    knowledgeEntitiesCount: 7,
  },
  {
    id: 'proj-datapipeline',
    name: 'StreamPulse ETL Engine',
    key: 'PULSE',
    description: 'Low-latency event streaming engine using Kafka and ClickHouse for real-time developer metrics analytics.',
    repositoryUrl: 'https://github.com/hayyuu-ai/streampulse-etl',
    branch: 'main',
    createdAt: '2026-05-04T16:40:00Z',
    updatedAt: '2026-08-05T18:30:00Z',
    status: 'Active',
    documentsCount: 2,
    requirementsCount: 4,
    tasksCount: 3,
    conflictsCount: 0,
    memoriesCount: 4,
    knowledgeEntitiesCount: 6,
  },
];

export const initialDocuments: Record<string, ProjectDocument[]> = {
  'proj-novapay': [
    {
      id: 'doc-01',
      projectId: 'proj-novapay',
      title: 'NovaPay Architecture Spec v2.1.pdf',
      fileName: 'novapay_arch_spec_v2.pdf',
      fileSize: '3.4 MB',
      fileType: 'PDF',
      uploadedAt: '2026-08-01T09:12:00Z',
      status: 'ready',
      chunksCount: 142,
      summary: 'Outlines the event-driven ledger architecture, Redis caching layer, PostgreSQL ACID transaction bounds, and gRPC internal interface spec.',
      extractedConcepts: ['gRPC Settlement', 'PostgreSQL Ledger', 'Redis Backpressure', 'Dead Letter Queue', 'HMAC Signatures'],
    },
    {
      id: 'doc-02',
      projectId: 'proj-novapay',
      title: 'Security and Compliance Framework 2026.docx',
      fileName: 'security_compliance_2026.docx',
      fileSize: '1.8 MB',
      fileType: 'DOCX',
      uploadedAt: '2026-08-03T14:30:00Z',
      status: 'ready',
      chunksCount: 88,
      summary: 'Details PCI-DSS v4.0 compliance requirements, hardware security module (HSM) tokenization, and strict 15-minute JWT token lifetime.',
      extractedConcepts: ['PCI-DSS v4.0', 'HSM Tokenization', 'JWT Expiration (15m)', 'Audit Trail Logging', 'mTLS Communication'],
    },
    {
      id: 'doc-03',
      projectId: 'proj-novapay',
      title: 'Fraud Detection Rules & ML Engine.md',
      fileName: 'fraud_detection_rules.md',
      fileSize: '420 KB',
      fileType: 'MARKDOWN',
      uploadedAt: '2026-08-05T11:00:00Z',
      status: 'ready',
      chunksCount: 34,
      summary: 'Defines rules for velocity checks, geofencing anomalies, and asynchronous model inference with sub-50ms latency SLAs.',
      extractedConcepts: ['Velocity Check', 'Geofencing Score', 'Inference SLA <50ms', 'Fallback Rule Engine'],
    },
    {
      id: 'doc-04',
      projectId: 'proj-novapay',
      title: 'Database Migration Schema Draft.sql',
      fileName: 'db_migration_schema_v3.sql',
      fileSize: '110 KB',
      fileType: 'SQL',
      uploadedAt: '2026-08-07T16:45:00Z',
      status: 'ready',
      chunksCount: 18,
      summary: 'Contains SQL schema scripts for idempotency key tracking, audit logs table partition by month, and ledger entries table.',
      extractedConcepts: ['Idempotency Keys', 'Partitioned Audit Table', 'Foreign Key Constraints'],
    },
    {
      id: 'doc-05',
      projectId: 'proj-novapay',
      title: 'Third-Party Bank Sandbox API Integration.json',
      fileName: 'bank_sandbox_swagger.json',
      fileSize: '850 KB',
      fileType: 'JSON',
      uploadedAt: '2026-08-09T10:15:00Z',
      status: 'processing',
      chunksCount: 0,
      summary: 'OpenAPI specification file currently being ingested and chunked into vector embeddings.',
      extractedConcepts: ['ISO 20022 Payloads', 'Webhook Callbacks'],
    },
  ],
  'proj-authservice': [
    {
      id: 'doc-auth-01',
      projectId: 'proj-authservice',
      title: 'OAuth2 & OIDC Implementation Spec.md',
      fileName: 'oauth2_oidc_spec.md',
      fileSize: '512 KB',
      fileType: 'MARKDOWN',
      uploadedAt: '2026-07-20T10:00:00Z',
      status: 'ready',
      chunksCount: 45,
      summary: 'Specifies PKCE flow for single page applications, refresh token rotation, and RS256 JWKS key publishing.',
      extractedConcepts: ['PKCE Authorization', 'RefreshToken Rotation', 'JWKS Endpoint'],
    },
  ],
};

export const initialRequirements: Record<string, Requirement[]> = {
  'proj-novapay': [
    {
      id: 'req-101',
      projectId: 'proj-novapay',
      title: 'Strict Sub-100ms API Settlement SLA',
      description: 'The payment settlement endpoint POST /api/v1/settle must complete financial authorization and return an idempotency receipt in under 100 milliseconds for 99.9% of requests.',
      type: 'Non-Functional',
      priority: 'Critical',
      status: 'Approved',
      source: 'NovaPay Architecture Spec v2.1.pdf',
      linkedDocIds: ['doc-01'],
      linkedTaskIds: ['task-201'],
      linkedKnowledgeIds: ['kn-01'],
      createdAt: '2026-08-01T10:00:00Z',
      updatedAt: '2026-08-02T12:00:00Z',
    },
    {
      id: 'req-102',
      projectId: 'proj-novapay',
      title: 'JWT Access Token Lifetime Limit',
      description: 'Access tokens issued for client applications must expire after exactly 15 minutes to strictly adhere to PCI-DSS compliance requirements.',
      type: 'Security',
      priority: 'High',
      status: 'Approved',
      source: 'Security and Compliance Framework 2026.docx',
      linkedDocIds: ['doc-02'],
      linkedTaskIds: ['task-202'],
      linkedKnowledgeIds: ['kn-02'],
      createdAt: '2026-08-03T15:00:00Z',
      updatedAt: '2026-08-04T09:30:00Z',
    },
    {
      id: 'req-103',
      projectId: 'proj-novapay',
      title: 'Extended Session Cache Duration for Offline Processing',
      description: 'User payment sessions should be cached in Redis with a 24-hour time-to-live to prevent auth roundtrips during offline retry queues.',
      type: 'Architecture',
      priority: 'Medium',
      status: 'In Review',
      source: 'Developer Note / Architectural Proposal',
      linkedDocIds: ['doc-01'],
      linkedTaskIds: [],
      linkedKnowledgeIds: ['kn-02'],
      createdAt: '2026-08-06T14:10:00Z',
      updatedAt: '2026-08-06T14:10:00Z',
    },
    {
      id: 'req-104',
      projectId: 'proj-novapay',
      title: 'Idempotency Key Enforcement on Settlement Endpoint',
      description: 'All POST requests to financial endpoints must mandate an Idempotency-Key header. Subsequent requests with identical keys must return the cached HTTP 200 payload without re-executing ledger operations.',
      type: 'Functional',
      priority: 'Critical',
      status: 'Approved',
      source: 'Database Migration Schema Draft.sql',
      linkedDocIds: ['doc-04'],
      linkedTaskIds: ['task-203'],
      linkedKnowledgeIds: ['kn-03'],
      createdAt: '2026-08-07T17:00:00Z',
      updatedAt: '2026-08-07T17:00:00Z',
    },
    {
      id: 'req-105',
      projectId: 'proj-novapay',
      title: 'Real-time Fraud Score Thresholding',
      description: 'Transactions with a fraud risk score above 85/100 must be immediately placed in manual review status, triggering a webhook event to compliance personnel.',
      type: 'Functional',
      priority: 'High',
      status: 'Approved',
      source: 'Fraud Detection Rules & ML Engine.md',
      linkedDocIds: ['doc-03'],
      linkedTaskIds: ['task-204'],
      linkedKnowledgeIds: ['kn-04'],
      createdAt: '2026-08-05T12:00:00Z',
      updatedAt: '2026-08-05T12:00:00Z',
    },
    {
      id: 'req-106',
      projectId: 'proj-novapay',
      title: 'Automated Monthly Audit Trail Archival',
      description: 'Audit logs older than 30 days must be automatically exported to immutable S3 Glacier cold storage with sha256 checksum verifications.',
      type: 'Non-Functional',
      priority: 'Low',
      status: 'Draft',
      source: 'Security and Compliance Framework 2026.docx',
      linkedDocIds: ['doc-02'],
      linkedTaskIds: [],
      linkedKnowledgeIds: [],
      createdAt: '2026-08-08T09:00:00Z',
      updatedAt: '2026-08-08T09:00:00Z',
    },
  ],
  'proj-authservice': [],
};

export const initialConflicts: Record<string, Conflict[]> = {
  'proj-novapay': [
    {
      id: 'conf-301',
      projectId: 'proj-novapay',
      title: 'JWT Session Token Expiration Contradiction',
      category: 'Contradiction',
      severity: 'High',
      status: 'Active',
      description: 'Security Requirement REQ-102 mandates a 15-minute max JWT token lifetime for PCI-DSS compliance, whereas Architecture Proposal REQ-103 mandates a 24-hour Redis session TTL for offline transaction queuing.',
      conflictingArtifacts: [
        { type: 'Requirement', title: 'REQ-102: JWT Access Token Lifetime Limit', id: 'req-102' },
        { type: 'Requirement', title: 'REQ-103: Extended Session Cache Duration', id: 'req-103' },
        { type: 'Document', title: 'Security and Compliance Framework 2026.docx', id: 'doc-02' },
      ],
      aiExplanation: 'The security policy forbids maintaining valid access tokens beyond 15 minutes, but the offline queue proposal assumes session tokens remain usable for up to 24 hours without re-authentication. This creates a security gap if unrevoked tokens persist in Redis.',
      suggestedAction: 'Separate short-lived OAuth access tokens (15 minutes) from encrypted offline idempotency refresh handles (24 hours stored in secure Redis cache with atomic invalidation).',
      detectedAt: '2026-08-06T15:30:00Z',
    },
    {
      id: 'conf-303',
      projectId: 'proj-novapay',
      title: 'Fraud ML Inference SLA vs Bank Callback Timeout Ambiguity',
      category: 'Ambiguity',
      severity: 'Low',
      status: 'Active',
      description: 'Fraud spec mandates sub-50ms inference, but the bank sandbox OpenAPI spec lists a 3000ms webhook callback window without defining behavior during timeout spikes.',
      conflictingArtifacts: [
        { type: 'Requirement', title: 'REQ-105: Real-time Fraud Score Thresholding', id: 'req-105' },
        { type: 'Document', title: 'Third-Party Bank Sandbox API Integration.json', id: 'doc-05' },
      ],
      aiExplanation: 'If the bank sandbox API takes 3 seconds to confirm callback signatures, the sub-100ms API settlement SLA (REQ-101) will fail unless fraud scoring executes asynchronously before external bank dispatches.',
      suggestedAction: 'Execute fraud scoring in a pre-settlement synchronous pipeline and trigger bank webhook callbacks asynchronously after returning HTTP 202 Accepted.',
      detectedAt: '2026-08-08T10:00:00Z',
    },
  ],
  'proj-authservice': [],
};

export const initialSuggestions: Record<string, AISuggestion[]> = {
  'proj-novapay': [
    {
      id: 'sug-401',
      projectId: 'proj-novapay',
      type: 'gap_analysis',
      content: {
        title: 'Unenforced Idempotency Key Schema in Database Migration',
        description: 'Functional Requirement REQ-104 mandates unique idempotency keys for all settlement transactions, but db_migration_schema_v3.sql lacks a UNIQUE index on the idempotency_key column.',
        reasoning: 'Without a UNIQUE database constraint on idempotency_key, concurrent API requests under high load could bypass application-layer checks and create duplicate financial transactions.',
        category: 'Gap Analysis / Reliability'
      },
      status: 'PENDING',
      createdAt: '2026-08-07T18:15:00Z',
      updatedAt: '2026-08-07T18:15:00Z'
    },
    {
      id: 'sug-402',
      projectId: 'proj-novapay',
      type: 'gap_analysis',
      content: {
        title: 'Implement Rate Limiting on Settle Endpoint',
        description: 'Add request rate limiting on the POST /api/v1/settle endpoint to prevent denial of service (DoS) attacks.',
        reasoning: 'The settlement endpoint executes expensive cryptographic validation and database row-level locking. Unrestricted traffic could easily exhaust the connection pool and CPU resources.',
        category: 'Security / Performance'
      },
      status: 'PENDING',
      createdAt: '2026-08-08T09:12:00Z',
      updatedAt: '2026-08-08T09:12:00Z'
    },
    {
      id: 'sug-403',
      projectId: 'proj-novapay',
      type: 'gap_analysis',
      content: {
        title: 'Introduce Distributed Tracing (OpenTelemetry)',
        description: 'Instrument gRPC settlement handlers with OpenTelemetry tracing spans to track latency metrics across Redis and PostgreSQL boundaries.',
        reasoning: 'REQ-101 requires a strict sub-100ms API SLA. Without detailed distributed trace telemetry, identifying which database query or cache fetch causes latency spikes under load will be extremely difficult.',
        category: 'Monitoring / Performance'
      },
      status: 'PENDING',
      createdAt: '2026-08-09T10:00:00Z',
      updatedAt: '2026-08-09T10:00:00Z'
    }
  ],
  'proj-authservice': [
    {
      id: 'sug-auth-01',
      projectId: 'proj-authservice',
      type: 'gap_analysis',
      content: {
        title: 'Enable PKCE for Mobile Ingress Clients',
        description: 'Enforce Authorization Code Flow with PKCE for all public OAuth2 clients.',
        reasoning: 'Mobile apps cannot securely store client secrets. Standard Authorization Code Flow without PKCE exposes them to interception attacks.',
        category: 'Security'
      },
      status: 'PENDING',
      createdAt: '2026-08-08T11:00:00Z',
      updatedAt: '2026-08-08T11:00:00Z'
    }
  ]
};

export const initialTasks: Record<string, Task[]> = {
  'proj-novapay': [
    {
      id: 'task-201',
      projectId: 'proj-novapay',
      title: 'Implement Redis Idempotency Middleware in Go',
      description: 'Create an HTTP middleware that extracts the Idempotency-Key header, checks Redis for cached responses, and locks concurrent duplicate executions.',
      status: 'In Progress',
      priority: 'Critical',
      linkedRequirementId: 'req-104',
      linkedDocId: 'doc-01',
      linkedGithubIssue: { id: 42, title: 'feat: Add idempotency header middleware', url: 'https://github.com/hayyuu-ai/novapay-core/issues/42' },
      tags: ['middleware', 'redis', 'golang', 'p0'],
      createdAt: '2026-08-02T11:00:00Z',
      updatedAt: '2026-08-08T16:00:00Z',
    },
    {
      id: 'task-202',
      projectId: 'proj-novapay',
      title: 'Configure RS256 JWT Token Verifier & 15m Expiration',
      description: 'Integrate JWKS public key rotation verifier and set token claims expiration to strict 900 seconds.',
      status: 'Done',
      priority: 'High',
      linkedRequirementId: 'req-102',
      linkedDocId: 'doc-02',
      tags: ['security', 'jwt', 'auth'],
      createdAt: '2026-08-03T16:00:00Z',
      updatedAt: '2026-08-05T10:30:00Z',
    },
    {
      id: 'task-203',
      projectId: 'proj-novapay',
      title: 'Add Unique Index to Idempotency Key Column',
      description: 'Fix migration schema script to add UNIQUE constraint on idempotency_key in PostgreSQL.',
      status: 'Todo',
      priority: 'High',
      linkedRequirementId: 'req-104',
      linkedDocId: 'doc-04',
      tags: ['database', 'postgresql', 'bugfix'],
      createdAt: '2026-08-07T19:00:00Z',
      updatedAt: '2026-08-07T19:00:00Z',
    },
    {
      id: 'task-204',
      projectId: 'proj-novapay',
      title: 'Implement Asynchronous Fraud Scoring Webhook Pipeline',
      description: 'Decouple fraud evaluation model call from synchronous settlement loop using RabbitMQ worker queue.',
      status: 'Backlog',
      priority: 'Medium',
      linkedRequirementId: 'req-105',
      linkedDocId: 'doc-03',
      tags: ['ml', 'async', 'rabbitmq'],
      createdAt: '2026-08-06T10:00:00Z',
      updatedAt: '2026-08-06T10:00:00Z',
    },
    {
      id: 'task-205',
      projectId: 'proj-novapay',
      title: 'Setup mTLS Cert Manager for Bank Webhook Ingress',
      description: 'Provision cert-manager and mutual TLS certificates for secure bank callback endpoints.',
      status: 'Backlog',
      priority: 'Low',
      tags: ['infrastructure', 'kubernetes', 'mtls'],
      createdAt: '2026-08-08T12:00:00Z',
      updatedAt: '2026-08-08T12:00:00Z',
    },
  ],
  'proj-authservice': [],
};

export const initialGitHubRepoInfo: Record<string, GitHubRepoInfo> = {
  'proj-novapay': {
    isConnected: true,
    repoName: 'hayyuu-ai/novapay-core',
    branch: 'main',
    lastSyncAt: '2026-08-09T23:45:00Z',
    openIssuesCount: 6,
    openPullRequestsCount: 2,
    recentCommits: [
      {
        hash: 'e8f12a4',
        message: 'feat(auth): enforce RS256 token verification with 15m expiration',
        author: 'Alex Rivera <alex.rivera@dev.hayyuu.ai>',
        date: '2026-08-08T18:20:00Z',
      },
      {
        hash: 'b4a91c0',
        message: 'fix(ledger): atomic transaction rollback on Redis connection timeout',
        author: 'Alex Rivera <alex.rivera@dev.hayyuu.ai>',
        date: '2026-08-07T14:10:00Z',
      },
      {
        hash: '3d7729e',
        message: 'docs: update OpenAPI specs for idempotency header requirements',
        author: 'Alex Rivera <alex.rivera@dev.hayyuu.ai>',
        date: '2026-08-06T09:45:00Z',
      },
    ],
    recentPRs: [
      {
        number: 14,
        title: 'PR #14: Add Redis Distributed Lock for Settlement Idempotency',
        status: 'open',
        author: 'arivera-dev',
        updatedAt: '2026-08-09T19:10:00Z',
      },
      {
        number: 12,
        title: 'PR #12: Update DB Schema Partitions for Monthly Audit Logs',
        status: 'merged',
        author: 'arivera-dev',
        updatedAt: '2026-08-07T11:30:00Z',
      },
    ],
    recentIssues: [
      {
        number: 42,
        title: 'Idempotency Key middleware fails under 5000 QPS concurrent stress test',
        state: 'open',
        labels: ['bug', 'performance', 'p0'],
      },
      {
        number: 38,
        title: 'Add health check endpoint for Kubernetes liveness probe',
        state: 'closed',
        labels: ['devops', 'enhancement'],
      },
    ],
    implementationSignals: [
      {
        requirementTitle: 'Strict Sub-100ms API Settlement SLA',
        implementationStatus: 'Synced',
        fileMatches: ['pkg/settlement/handler.go', 'pkg/settlement/bench_test.go'],
        lastChecked: '2026-08-09T23:45:00Z',
      },
      {
        requirementTitle: 'JWT Access Token Lifetime Limit',
        implementationStatus: 'Synced',
        fileMatches: ['internal/auth/jwt_verifier.go'],
        lastChecked: '2026-08-09T23:45:00Z',
      },
      {
        requirementTitle: 'Idempotency Key Enforcement on Settlement Endpoint',
        implementationStatus: 'Drift Detected',
        fileMatches: ['pkg/middleware/idempotency.go'],
        lastChecked: '2026-08-09T23:45:00Z',
      },
      {
        requirementTitle: 'Extended Session Cache Duration for Offline Processing',
        implementationStatus: 'Unlinked',
        fileMatches: [],
        lastChecked: '2026-08-09T23:45:00Z',
      },
    ],
  },
  'proj-authservice': {
    isConnected: true,
    repoName: 'hayyuu-ai/auth-service',
    branch: 'main',
    lastSyncAt: '2026-08-08T10:00:00Z',
    openIssuesCount: 2,
    openPullRequestsCount: 1,
    recentCommits: [],
    recentPRs: [],
    recentIssues: [],
    implementationSignals: [],
  },
};

export const initialKnowledgeEntities: Record<string, KnowledgeEntity[]> = {
  'proj-novapay': [
    {
      id: 'kn-01',
      projectId: 'proj-novapay',
      name: 'gRPC Settlement Service',
      type: 'Architecture',
      description: 'High performance internal RPC channel handling settlement transactions with protobuf v3 contracts.',
      source: 'NovaPay Architecture Spec v2.1.pdf',
      confidence: 0.98,
      relatedEntityIds: ['kn-02', 'kn-03'],
      linkedArtifacts: [
        { type: 'Requirement', title: 'REQ-101: Sub-100ms Settlement SLA' },
        { type: 'Document', title: 'novapay_arch_spec_v2.pdf' },
      ],
      createdAt: '2026-08-01T10:30:00Z',
    },
    {
      id: 'kn-02',
      projectId: 'proj-novapay',
      name: 'Redis Distributed Lock Engine',
      type: 'Component',
      description: 'In-memory caching and Redlock distributed locking mechanism guaranteeing single execution for idempotency keys.',
      source: 'NovaPay Architecture Spec v2.1.pdf',
      confidence: 0.95,
      relatedEntityIds: ['kn-01', 'kn-03'],
      linkedArtifacts: [
        { type: 'Task', title: 'Implement Redis Idempotency Middleware' },
        { type: 'Requirement', title: 'REQ-104: Idempotency Key Enforcement' },
      ],
      createdAt: '2026-08-02T11:15:00Z',
    },
    {
      id: 'kn-03',
      projectId: 'proj-novapay',
      name: 'PostgreSQL ACID Ledger Table',
      type: 'Technology',
      description: 'Relational storage table with partitioned monthly ledgers and transactional row-level locks for monetary balance updates.',
      source: 'Database Migration Schema Draft.sql',
      confidence: 0.99,
      relatedEntityIds: ['kn-01'],
      linkedArtifacts: [{ type: 'Document', title: 'db_migration_schema_v3.sql' }],
      createdAt: '2026-08-07T17:30:00Z',
    },
    {
      id: 'kn-04',
      projectId: 'proj-novapay',
      name: 'ML Fraud Score Model (Sub-50ms)',
      type: 'Pattern',
      description: 'Asynchronous XGBoost model evaluating user transaction velocity, IP geolocation, and device telemetry.',
      source: 'Fraud Detection Rules & ML Engine.md',
      confidence: 0.92,
      relatedEntityIds: ['kn-01'],
      linkedArtifacts: [{ type: 'Requirement', title: 'REQ-105: Fraud Score Thresholding' }],
      createdAt: '2026-08-05T12:30:00Z',
    },
    {
      id: 'kn-05',
      projectId: 'proj-novapay',
      name: 'RS256 JWKS Authorization Provider',
      type: 'API',
      description: 'Asymmetric cryptographic key signature validator executing zero-trust Bearer token validation on API endpoints.',
      source: 'Security and Compliance Framework 2026.docx',
      confidence: 0.97,
      relatedEntityIds: [],
      linkedArtifacts: [{ type: 'Requirement', title: 'REQ-102: JWT Token Lifetime Limit' }],
      createdAt: '2026-08-03T15:45:00Z',
    },
  ],
  'proj-authservice': [],
};

export const initialKnowledgeRelations: Record<string, KnowledgeRelation[]> = {
  'proj-novapay': [
    {
      id: 'rel-01',
      sourceId: 'kn-01',
      targetId: 'kn-02',
      relationType: 'depends_on',
      description: 'gRPC Settlement service checks Redis Distributed Lock prior to modifying financial ledgers.',
    },
    {
      id: 'rel-02',
      sourceId: 'kn-01',
      targetId: 'kn-03',
      relationType: 'implements',
      description: 'gRPC Settlement service persists settled transaction payloads directly to PostgreSQL Ledger Table.',
    },
    {
      id: 'rel-03',
      sourceId: 'kn-04',
      targetId: 'kn-01',
      relationType: 'references',
      description: 'Fraud Score Model intercepts gRPC payload data for risk scoring.',
    },
  ],
  'proj-authservice': [],
};

export const initialMemoryItems: Record<string, MemoryItem[]> = {
  'proj-novapay': [
    {
      id: 'mem-01',
      projectId: 'proj-novapay',
      type: 'working',
      summary: 'Current Context: Resolving Idempotency Middleware Drift',
      content: 'Developer is currently investigating conflict CONF-301 regarding JWT 15m lifetime vs 24h offline cache, while preparing PR #14 for Redis Distributed Lock.',
      source: 'Active AI Chat Session #3',
      relevanceScore: 0.99,
      createdAt: '2026-08-09T22:10:00Z',
      updatedAt: '2026-08-09T23:50:00Z',
    },
    {
      id: 'mem-02',
      projectId: 'proj-novapay',
      type: 'short_term',
      summary: 'Decision: Adopt RS256 Asymmetric Keys for mTLS Microservices',
      content: 'During architecture review on Aug 3, team decided RS256 JWKS endpoints will be hosted at https://auth.novapay.internal/.well-known/jwks.json.',
      source: 'Document Ingestion: Security Framework 2026',
      relevanceScore: 0.92,
      createdAt: '2026-08-03T16:00:00Z',
      updatedAt: '2026-08-03T16:00:00Z',
    },
    {
      id: 'mem-03',
      projectId: 'proj-novapay',
      type: 'long_term',
      summary: 'PCI-DSS Compliance Mandate v4.0 Requirement',
      content: 'All financial audit logs must maintain sha256 checksums and be stored in monthly partitioned database tables with immutable S3 Glacier exports.',
      source: 'Security Policy Compliance Engine',
      relevanceScore: 0.88,
      createdAt: '2026-08-01T11:00:00Z',
      updatedAt: '2026-08-01T11:00:00Z',
    },
    {
      id: 'mem-04',
      projectId: 'proj-novapay',
      type: 'episodic',
      summary: 'Stress Test Benchmark Failure at 5000 QPS',
      content: 'In GitHub Issue #42, developer reported that without UNIQUE database constraint on idempotency_key, Redis lock contention caused 1.2% duplicate ledger insertions under peak load.',
      source: 'GitHub Sync Integration',
      relevanceScore: 0.94,
      createdAt: '2026-08-08T15:30:00Z',
      updatedAt: '2026-08-08T15:30:00Z',
    },
    {
      id: 'mem-05',
      projectId: 'proj-novapay',
      type: 'semantic',
      summary: 'Core Concept: Idempotency Key Handling in Financial Systems',
      content: 'Idempotency guarantees that initiating the same API payment request multiple times results in the exact same output without duplicate side-effects or charges.',
      source: 'Hayyuu AI Engineering Knowledge Base',
      relevanceScore: 0.85,
      createdAt: '2026-08-01T10:00:00Z',
      updatedAt: '2026-08-01T10:00:00Z',
    },
  ],
  'proj-authservice': [],
};

export const initialConversations: Record<string, Conversation[]> = {
  'proj-novapay': [
    {
      id: 'conv-01',
      projectId: 'proj-novapay',
      title: 'Idempotency & Session Token Expiration Conflict Analysis',
      createdAt: '2026-08-09T21:00:00Z',
      updatedAt: '2026-08-09T23:50:00Z',
      messages: [
        {
          id: 'msg-01',
          conversationId: 'conv-01',
          role: 'user',
          content: 'Hayyuu, can you analyze why there is a conflict between our security requirements and session cache duration proposal?',
          timestamp: '2026-08-09T21:01:00Z',
        },
        {
          id: 'msg-02',
          conversationId: 'conv-01',
          role: 'assistant',
          content: `I've analyzed your project artifacts and detected a **Critical Security & Architecture Contradiction** (Conflict CONF-301):

### 🔍 Identified Conflict
- **Requirement REQ-102 (Security)** mandates a strict **15-minute maximum lifetime** for JWT access tokens to maintain PCI-DSS v4.0 compliance (*Security Framework v2026.docx*).
- **Requirement REQ-103 (Proposal)** suggests holding user payment sessions in Redis with a **24-hour TTL** for offline processing retries.

### ⚠️ Risk Analysis
If a client application uses a single token for both standard authentication and long-lived offline queuing, compromised 24-hour tokens in Redis could allow unauthorized settlement execution past the 15-minute PCI-DSS boundary.

### 💡 Recommended Resolution
1. Keep JWT Access Tokens short-lived (**15 minutes max**).
2. For offline queue operations, issue an encrypted **Idempotency Execution Handle** stored in Redis with atomic single-use invalidation rather than storing raw authorization tokens.`,
          timestamp: '2026-08-09T21:01:15Z',
          retrievedContext: {
            requirements: [
              { id: 'req-102', title: 'REQ-102: JWT Access Token Lifetime Limit', type: 'Security' },
              { id: 'req-103', title: 'REQ-103: Extended Session Cache Duration', type: 'Architecture' },
            ],
            documents: [
              { id: 'doc-02', title: 'Security and Compliance Framework 2026.docx', excerpt: 'JWT token lifetime must not exceed 900 seconds...' },
            ],
            memories: [
              { summary: 'Decision: Adopt RS256 Asymmetric Keys', type: 'short_term' },
            ],
            github: [
              { repo: 'hayyuu-ai/novapay-core', branch: 'main', commit: 'e8f12a4' },
            ],
          },
          reasoningSummary: 'Retrieved REQ-102 and REQ-103 from vector memory index. Verified conflict against PCI-DSS v4.0 spec and checked PR #14 in GitHub.',
          toolsUsed: ['vector_search', 'graph_query', 'github_signal_checker'],
        },
      ],
    },
  ],
  'proj-authservice': [],
};

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-01',
    title: 'Document Processing Complete',
    message: 'NovaPay Architecture Spec v2.1.pdf was successfully processed and indexed into 142 vector chunks.',
    type: 'success',
    read: false,
    timestamp: '2026-08-09T23:30:00Z',
    actionSection: 'documents',
  },
  {
    id: 'notif-02',
    title: 'High Severity Conflict Detected',
    message: 'Conflict CONF-301: Contradiction between REQ-102 (JWT Lifetime) and REQ-103 (Session Cache TTL).',
    type: 'warning',
    read: false,
    timestamp: '2026-08-09T21:05:00Z',
    actionSection: 'conflicts',
  },
  {
    id: 'notif-03',
    title: 'GitHub Sync Updated',
    message: 'Synced 3 new commits and 1 open PR from repository hayyuu-ai/novapay-core.',
    type: 'info',
    read: true,
    timestamp: '2026-08-09T19:15:00Z',
    actionSection: 'github',
  },
];

export const initialWorkflowJobs: WorkflowJob[] = [
  {
    id: 'job-101',
    name: 'Third-Party Bank Sandbox Swagger Ingestion',
    status: 'running',
    progress: 68,
    startedAt: '2026-08-09T23:55:00Z',
    details: 'Parsing OpenAPI endpoints, extracting payload schemas, and generating vector embeddings...',
  },
  {
    id: 'job-102',
    name: 'GitHub Repository Codebase Knowledge Extraction',
    status: 'completed',
    progress: 100,
    startedAt: '2026-08-09T23:40:00Z',
    details: 'Successfully mapped 4 files to requirement signals.',
  },
];
